version: '3'
services:
    app:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/code
        depends_on:
            - db
#        environment:
#            SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:pwd@db/codetogive
        #entrypoint: ['/usr/src/app/entrypoint.sh']
        networks:
            - flaskapp

    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: pwd
            POSTGRES_DB: codetogive
        ports:
            - "5432:5432"
        networks:
            - flaskapp

networks:
    flaskapp:
        driver: bridge
