# Generated by Django 4.0 on 2022-01-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propic',
            field=models.ImageField(default='user.png', upload_to='profile_pics'),
        ),
    ]
